/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as DemoSnapshotRouteImport } from './routes/demo-snapshot'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FactsIndexRouteImport } from './routes/facts.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiPropertyHierarchyRouteImport } from './routes/api/property-hierarchy'
import { Route as ApiPropertyHierarchiesRouteImport } from './routes/api/property-hierarchies'
import { Route as ApiPropertiesRouteImport } from './routes/api/properties'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiFactsRouteImport } from './routes/api/facts'
import { Route as ApiCasesRouteImport } from './routes/api/cases'
import { Route as FactsScopeTypeScopeIdRouteImport } from './routes/facts.$scopeType.$scopeId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiCasesCaseIdRouteImport } from './routes/api/cases.$caseId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCasesCaseIdAgentStreamRouteImport } from './routes/api/cases.$caseId.agent-stream'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSnapshotRoute = DemoSnapshotRouteImport.update({
  id: '/demo-snapshot',
  path: '/demo-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsIndexRoute = FactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FactsRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyHierarchyRoute = ApiPropertyHierarchyRouteImport.update({
  id: '/api/property-hierarchy',
  path: '/api/property-hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyHierarchiesRoute = ApiPropertyHierarchiesRouteImport.update({
  id: '/api/property-hierarchies',
  path: '/api/property-hierarchies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesRoute = ApiPropertiesRouteImport.update({
  id: '/api/properties',
  path: '/api/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFactsRoute = ApiFactsRouteImport.update({
  id: '/api/facts',
  path: '/api/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesRoute = ApiCasesRouteImport.update({
  id: '/api/cases',
  path: '/api/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsScopeTypeScopeIdRoute = FactsScopeTypeScopeIdRouteImport.update({
  id: '/$scopeType/$scopeId',
  path: '/$scopeType/$scopeId',
  getParentRoute: () => FactsRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesCaseIdRoute = ApiCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => ApiCasesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesCaseIdAgentStreamRoute =
  ApiCasesCaseIdAgentStreamRouteImport.update({
    id: '/agent-stream',
    path: '/agent-stream',
    getParentRoute: () => ApiCasesCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases': typeof CasesRouteWithChildren
  '/demo-snapshot': typeof DemoSnapshotRoute
  '/facts': typeof FactsRouteWithChildren
  '/search': typeof SearchRoute
  '/api/cases': typeof ApiCasesRouteWithChildren
  '/api/facts': typeof ApiFactsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/property-hierarchies': typeof ApiPropertyHierarchiesRoute
  '/api/property-hierarchy': typeof ApiPropertyHierarchyRoute
  '/api/search': typeof ApiSearchRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/cases/': typeof CasesIndexRoute
  '/facts/': typeof FactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cases/$caseId': typeof ApiCasesCaseIdRouteWithChildren
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/facts/$scopeType/$scopeId': typeof FactsScopeTypeScopeIdRoute
  '/api/cases/$caseId/agent-stream': typeof ApiCasesCaseIdAgentStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo-snapshot': typeof DemoSnapshotRoute
  '/search': typeof SearchRoute
  '/api/cases': typeof ApiCasesRouteWithChildren
  '/api/facts': typeof ApiFactsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/property-hierarchies': typeof ApiPropertyHierarchiesRoute
  '/api/property-hierarchy': typeof ApiPropertyHierarchyRoute
  '/api/search': typeof ApiSearchRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/cases': typeof CasesIndexRoute
  '/facts': typeof FactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cases/$caseId': typeof ApiCasesCaseIdRouteWithChildren
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/facts/$scopeType/$scopeId': typeof FactsScopeTypeScopeIdRoute
  '/api/cases/$caseId/agent-stream': typeof ApiCasesCaseIdAgentStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases': typeof CasesRouteWithChildren
  '/demo-snapshot': typeof DemoSnapshotRoute
  '/facts': typeof FactsRouteWithChildren
  '/search': typeof SearchRoute
  '/api/cases': typeof ApiCasesRouteWithChildren
  '/api/facts': typeof ApiFactsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/property-hierarchies': typeof ApiPropertyHierarchiesRoute
  '/api/property-hierarchy': typeof ApiPropertyHierarchyRoute
  '/api/search': typeof ApiSearchRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/cases/': typeof CasesIndexRoute
  '/facts/': typeof FactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cases/$caseId': typeof ApiCasesCaseIdRouteWithChildren
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/facts/$scopeType/$scopeId': typeof FactsScopeTypeScopeIdRoute
  '/api/cases/$caseId/agent-stream': typeof ApiCasesCaseIdAgentStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cases'
    | '/demo-snapshot'
    | '/facts'
    | '/search'
    | '/api/cases'
    | '/api/facts'
    | '/api/mcp'
    | '/api/properties'
    | '/api/property-hierarchies'
    | '/api/property-hierarchy'
    | '/api/search'
    | '/cases/$caseId'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/cases/'
    | '/facts/'
    | '/api/auth/$'
    | '/api/cases/$caseId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/facts/$scopeType/$scopeId'
    | '/api/cases/$caseId/agent-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo-snapshot'
    | '/search'
    | '/api/cases'
    | '/api/facts'
    | '/api/mcp'
    | '/api/properties'
    | '/api/property-hierarchies'
    | '/api/property-hierarchy'
    | '/api/search'
    | '/cases/$caseId'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/cases'
    | '/facts'
    | '/api/auth/$'
    | '/api/cases/$caseId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/facts/$scopeType/$scopeId'
    | '/api/cases/$caseId/agent-stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cases'
    | '/demo-snapshot'
    | '/facts'
    | '/search'
    | '/api/cases'
    | '/api/facts'
    | '/api/mcp'
    | '/api/properties'
    | '/api/property-hierarchies'
    | '/api/property-hierarchy'
    | '/api/search'
    | '/cases/$caseId'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/cases/'
    | '/facts/'
    | '/api/auth/$'
    | '/api/cases/$caseId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/facts/$scopeType/$scopeId'
    | '/api/cases/$caseId/agent-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CasesRoute: typeof CasesRouteWithChildren
  DemoSnapshotRoute: typeof DemoSnapshotRoute
  FactsRoute: typeof FactsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ApiCasesRoute: typeof ApiCasesRouteWithChildren
  ApiFactsRoute: typeof ApiFactsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPropertiesRoute: typeof ApiPropertiesRoute
  ApiPropertyHierarchiesRoute: typeof ApiPropertyHierarchiesRoute
  ApiPropertyHierarchyRoute: typeof ApiPropertyHierarchyRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-snapshot': {
      id: '/demo-snapshot'
      path: '/demo-snapshot'
      fullPath: '/demo-snapshot'
      preLoaderRoute: typeof DemoSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts/': {
      id: '/facts/'
      path: '/'
      fullPath: '/facts/'
      preLoaderRoute: typeof FactsIndexRouteImport
      parentRoute: typeof FactsRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-hierarchy': {
      id: '/api/property-hierarchy'
      path: '/api/property-hierarchy'
      fullPath: '/api/property-hierarchy'
      preLoaderRoute: typeof ApiPropertyHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-hierarchies': {
      id: '/api/property-hierarchies'
      path: '/api/property-hierarchies'
      fullPath: '/api/property-hierarchies'
      preLoaderRoute: typeof ApiPropertyHierarchiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties': {
      id: '/api/properties'
      path: '/api/properties'
      fullPath: '/api/properties'
      preLoaderRoute: typeof ApiPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facts': {
      id: '/api/facts'
      path: '/api/facts'
      fullPath: '/api/facts'
      preLoaderRoute: typeof ApiFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases': {
      id: '/api/cases'
      path: '/api/cases'
      fullPath: '/api/cases'
      preLoaderRoute: typeof ApiCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts/$scopeType/$scopeId': {
      id: '/facts/$scopeType/$scopeId'
      path: '/$scopeType/$scopeId'
      fullPath: '/facts/$scopeType/$scopeId'
      preLoaderRoute: typeof FactsScopeTypeScopeIdRouteImport
      parentRoute: typeof FactsRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/$caseId': {
      id: '/api/cases/$caseId'
      path: '/$caseId'
      fullPath: '/api/cases/$caseId'
      preLoaderRoute: typeof ApiCasesCaseIdRouteImport
      parentRoute: typeof ApiCasesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/$caseId/agent-stream': {
      id: '/api/cases/$caseId/agent-stream'
      path: '/agent-stream'
      fullPath: '/api/cases/$caseId/agent-stream'
      preLoaderRoute: typeof ApiCasesCaseIdAgentStreamRouteImport
      parentRoute: typeof ApiCasesCaseIdRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface FactsRouteChildren {
  FactsIndexRoute: typeof FactsIndexRoute
  FactsScopeTypeScopeIdRoute: typeof FactsScopeTypeScopeIdRoute
}

const FactsRouteChildren: FactsRouteChildren = {
  FactsIndexRoute: FactsIndexRoute,
  FactsScopeTypeScopeIdRoute: FactsScopeTypeScopeIdRoute,
}

const FactsRouteWithChildren = FactsRoute._addFileChildren(FactsRouteChildren)

interface ApiCasesCaseIdRouteChildren {
  ApiCasesCaseIdAgentStreamRoute: typeof ApiCasesCaseIdAgentStreamRoute
}

const ApiCasesCaseIdRouteChildren: ApiCasesCaseIdRouteChildren = {
  ApiCasesCaseIdAgentStreamRoute: ApiCasesCaseIdAgentStreamRoute,
}

const ApiCasesCaseIdRouteWithChildren = ApiCasesCaseIdRoute._addFileChildren(
  ApiCasesCaseIdRouteChildren,
)

interface ApiCasesRouteChildren {
  ApiCasesCaseIdRoute: typeof ApiCasesCaseIdRouteWithChildren
}

const ApiCasesRouteChildren: ApiCasesRouteChildren = {
  ApiCasesCaseIdRoute: ApiCasesCaseIdRouteWithChildren,
}

const ApiCasesRouteWithChildren = ApiCasesRoute._addFileChildren(
  ApiCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CasesRoute: CasesRouteWithChildren,
  DemoSnapshotRoute: DemoSnapshotRoute,
  FactsRoute: FactsRouteWithChildren,
  SearchRoute: SearchRoute,
  ApiCasesRoute: ApiCasesRouteWithChildren,
  ApiFactsRoute: ApiFactsRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPropertiesRoute: ApiPropertiesRoute,
  ApiPropertyHierarchiesRoute: ApiPropertyHierarchiesRoute,
  ApiPropertyHierarchyRoute: ApiPropertyHierarchyRoute,
  ApiSearchRoute: ApiSearchRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
