/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiPropertyHierarchyRouteImport } from './routes/api/property-hierarchy'
import { Route as ApiPropertyHierarchiesRouteImport } from './routes/api/property-hierarchies'
import { Route as ApiPropertiesRouteImport } from './routes/api/properties'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiFactsRouteImport } from './routes/api/facts'
import { Route as ApiCasesRouteImport } from './routes/api/cases'
import { Route as FactsScopeTypeScopeIdRouteImport } from './routes/facts.$scopeType.$scopeId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyHierarchyRoute = ApiPropertyHierarchyRouteImport.update({
  id: '/api/property-hierarchy',
  path: '/api/property-hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyHierarchiesRoute = ApiPropertyHierarchiesRouteImport.update({
  id: '/api/property-hierarchies',
  path: '/api/property-hierarchies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesRoute = ApiPropertiesRouteImport.update({
  id: '/api/properties',
  path: '/api/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFactsRoute = ApiFactsRouteImport.update({
  id: '/api/facts',
  path: '/api/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesRoute = ApiCasesRouteImport.update({
  id: '/api/cases',
  path: '/api/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsScopeTypeScopeIdRoute = FactsScopeTypeScopeIdRouteImport.update({
  id: '/$scopeType/$scopeId',
  path: '/$scopeType/$scopeId',
  getParentRoute: () => FactsRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases': typeof CasesRoute
  '/facts': typeof FactsRouteWithChildren
  '/api/cases': typeof ApiCasesRoute
  '/api/facts': typeof ApiFactsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/property-hierarchies': typeof ApiPropertyHierarchiesRoute
  '/api/property-hierarchy': typeof ApiPropertyHierarchyRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/facts/$scopeType/$scopeId': typeof FactsScopeTypeScopeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases': typeof CasesRoute
  '/facts': typeof FactsRouteWithChildren
  '/api/cases': typeof ApiCasesRoute
  '/api/facts': typeof ApiFactsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/property-hierarchies': typeof ApiPropertyHierarchiesRoute
  '/api/property-hierarchy': typeof ApiPropertyHierarchyRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/facts/$scopeType/$scopeId': typeof FactsScopeTypeScopeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases': typeof CasesRoute
  '/facts': typeof FactsRouteWithChildren
  '/api/cases': typeof ApiCasesRoute
  '/api/facts': typeof ApiFactsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/property-hierarchies': typeof ApiPropertyHierarchiesRoute
  '/api/property-hierarchy': typeof ApiPropertyHierarchyRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/facts/$scopeType/$scopeId': typeof FactsScopeTypeScopeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cases'
    | '/facts'
    | '/api/cases'
    | '/api/facts'
    | '/api/mcp'
    | '/api/properties'
    | '/api/property-hierarchies'
    | '/api/property-hierarchy'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/facts/$scopeType/$scopeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cases'
    | '/facts'
    | '/api/cases'
    | '/api/facts'
    | '/api/mcp'
    | '/api/properties'
    | '/api/property-hierarchies'
    | '/api/property-hierarchy'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/facts/$scopeType/$scopeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cases'
    | '/facts'
    | '/api/cases'
    | '/api/facts'
    | '/api/mcp'
    | '/api/properties'
    | '/api/property-hierarchies'
    | '/api/property-hierarchy'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/facts/$scopeType/$scopeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CasesRoute: typeof CasesRoute
  FactsRoute: typeof FactsRouteWithChildren
  ApiCasesRoute: typeof ApiCasesRoute
  ApiFactsRoute: typeof ApiFactsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPropertiesRoute: typeof ApiPropertiesRoute
  ApiPropertyHierarchiesRoute: typeof ApiPropertyHierarchiesRoute
  ApiPropertyHierarchyRoute: typeof ApiPropertyHierarchyRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-hierarchy': {
      id: '/api/property-hierarchy'
      path: '/api/property-hierarchy'
      fullPath: '/api/property-hierarchy'
      preLoaderRoute: typeof ApiPropertyHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-hierarchies': {
      id: '/api/property-hierarchies'
      path: '/api/property-hierarchies'
      fullPath: '/api/property-hierarchies'
      preLoaderRoute: typeof ApiPropertyHierarchiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties': {
      id: '/api/properties'
      path: '/api/properties'
      fullPath: '/api/properties'
      preLoaderRoute: typeof ApiPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facts': {
      id: '/api/facts'
      path: '/api/facts'
      fullPath: '/api/facts'
      preLoaderRoute: typeof ApiFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases': {
      id: '/api/cases'
      path: '/api/cases'
      fullPath: '/api/cases'
      preLoaderRoute: typeof ApiCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts/$scopeType/$scopeId': {
      id: '/facts/$scopeType/$scopeId'
      path: '/$scopeType/$scopeId'
      fullPath: '/facts/$scopeType/$scopeId'
      preLoaderRoute: typeof FactsScopeTypeScopeIdRouteImport
      parentRoute: typeof FactsRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FactsRouteChildren {
  FactsScopeTypeScopeIdRoute: typeof FactsScopeTypeScopeIdRoute
}

const FactsRouteChildren: FactsRouteChildren = {
  FactsScopeTypeScopeIdRoute: FactsScopeTypeScopeIdRoute,
}

const FactsRouteWithChildren = FactsRoute._addFileChildren(FactsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CasesRoute: CasesRoute,
  FactsRoute: FactsRouteWithChildren,
  ApiCasesRoute: ApiCasesRoute,
  ApiFactsRoute: ApiFactsRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPropertiesRoute: ApiPropertiesRoute,
  ApiPropertyHierarchiesRoute: ApiPropertyHierarchiesRoute,
  ApiPropertyHierarchyRoute: ApiPropertyHierarchyRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
